### ISSUE TITLE
Beta's bugs - Round # 4

### ISSUE THREAD

**Issue by elzadj** [maxi-blocks/maxiblocks-theme#1]
https://github.com/maxi-blocks/maxi-blocks/issues/5555

**Comment by ckp267** [comment]
Here is the summary of issues that need attention in a numbered list, ready to be added to GitHub:

Prompt: Used in Groq Lama 3 70B https://groq.com/ 305.37 Tokens per seconds

> Role: Professional QA tester and github issue creators.
> Task: please summarize all the issues that need attention in this chat thread
> 1. a numbered list so i can add them to github. 
> 2. Add a placeholder for images when missing. 
> 3. Note speaker names. Retain key details like browsers etc
> Format: Output numbered list in markdown ready for a github issue.

**Issues:**

1. **Crash in Site Editor**: Crash occurs when trying to open the pages view in Firefox. Christiaan, 11:23
	* **Browser:** Firefox
	* **Error:** React errors
![firefox_obbfo0NG0Q](https://github.com/maxi-blocks/maxiblocks-theme/assets/7437580/cfcf5678-3b31-4b0c-a45c-a6cadc8825f0)

2. **DeadObject error**: Error occurs in Firefox. Christiaan, 11:27
	* **Browser:** Firefox
	* **Error:** DeadObject
	
3. **Slow loading in Firefox**: Site Editor loads slowly in Firefox compared to Chrome. Christiaan, 11:42
	* **Browser:** Firefox
	* **Issue:** Slow loading
4. **Missing image on 404 page**: One image is missing on the 404 page. Christiaan, 11:43
	* **Page:** 404
	* **Issue:** Missing image
5. **Page Editor styles**: Page Editor styles are odd, and the title is left-aligned. Christiaan, 11:49
	* **Page:** Page Editor
	* **Issue:** Styles and title alignment
6. **EE title alignment**: Title is left-aligned in EE. Christiaan, 59 min
	* **Page:** EE
	* **Issue:** Title alignment
7. **EDGE EE infinite SVG migrator loop**: Infinite SVG migrator loop occurs in EDGE EE, taking around 5 minutes to stop before the console loads for errors. Christiaan, 8 min
	* **Browser:** Chrome
	* **Page:** EE
	* **Issue:** Infinite SVG migrator loop
![msedge_wfGrqF5cJq](https://github.com/maxi-blocks/maxiblocks-theme/assets/7437580/d625df04-2bf2-4112-96c9-025e9e4c3903)
![msedge_ZeTPbu4DTM](https://github.com/maxi-blocks/maxiblocks-theme/assets/7437580/7f2d4ad3-8674-47d6-b6aa-d91c5cc745aa)
![msedge_k0a8Xlx0cH](https://github.com/maxi-blocks/maxiblocks-theme/assets/7437580/2f462d96-763f-4c79-bb80-459183613b22)


**Notes:**

* **Browsers:** Firefox, Chrome, Edge
* **Pages:** Site Editor, EE, 404
* **Speakers:** Christiaan, Svitlana, Kyra

**Comment by kyrapieterse** [comment]
![image](https://github.com/maxi-blocks/maxiblocks-theme/assets/2478274/8c5da838-61e8-45a9-840a-dc13c5b4bccb)

**Comment by elzadj** [comment]
- [ ] Customize(r) rename or hide (need to find an alternative to custom css then).
- [ ] New Page editor load delay before you can type / add blocks.
- [ ] Styles for 'Add title' and 'Type / to choose a block' (see above).
- [ ] New custom template - patterns pop-up - need a preview (most likely the index one).
- [ ] Theme styles affecting font size for native blocks.
- [ ] Check what we need from the custom SC we provide, maybe we can add it to the default sc.
- [ ] Insert pattern to a page - click some blocks, they reload on click (check unique id).
- [ ] Open Block inserter - Patterns - click a pattern - nothing happens until it starts rendering. Need a loading indicator, or something.

**Comment by elzadj** [comment]
CPT templates https://github.com/maxi-blocks/maxi-blocks/issues/5587

**Comment by Olekrut** [comment]
native blocks do not have enough settings to remove some styles and fix everything for a really long time, but maybe for example, native content block needs to remove the margin it will definitely be used
![image](https://github.com/maxi-blocks/maxiblocks-theme/assets/88893350/162ab5de-7113-47d6-aece-80daf196f12f)

**Comment by ckp267** [comment]
> native blocks do not have enough settings to remove some styles and fix everything for a really long time, but maybe for example, native content block needs to remove the margin it will definitely be used ![image](https://private-user-images.githubusercontent.com/88893350/335621386-162ab5de-7113-47d6-aece-80daf196f12f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNjk0MTUsIm5iZiI6MTcxNzE2OTExNSwicGF0aCI6Ii84ODg5MzM1MC8zMzU2MjEzODYtMTYyYWI1ZGUtNzExMy00N2Q2LWFlY2UtODBkYWYxOTZmMTJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDE1MjUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczZmE5ZmUyOTdjZmU3MDhmOGIwMWYzYTJiMTY0ODdkNDZlZTExY2QyMDBkZGMzMjQ0Y2JkMjIxOGRmYTc3MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B0xRhrkCWAGumNBjpOcbEpboOTfn2-z_kO7dq6f61IA)

Have you tried the Styles Section in the site editor? I saw some blocks start styles there. 
I wonder if we can update (margin-block-start: 24px) in our theme.json file @elzadj @Olekrut ?

**Comment by elzadj** [comment]
> I wonder if we can update (margin-block-start: 24px) in our theme.json file
there is no such thing there, but I can add styles for the entry-content area to make it 0

**Comment by ckp267** [comment]
https://maxitheme.instawp.xyz/wp-admin/post.php?post=18&action=edit

![image](https://github.com/maxi-blocks/maxiblocks-theme/assets/7437580/3925c650-283e-4066-9cb8-5c9064947560)

![image](https://github.com/maxi-blocks/maxiblocks-theme/assets/7437580/8eb04237-6f02-4be0-bb15-e40ddac4c827)

console logs 
[index-template-edit-block-crash-chrome-console.txt](https://github.com/user-attachments/files/15567988/index-template-edit-block-crash-chrome-console.txt)

error log on theme activation.

[04-Jun-2024 16:30:34 UTC] PHP Deprecated:  Automatic conversion of false to array is deprecated in /home/dasaguyuro9895/web/maxitheme.instawp.xyz/public_html/wp-content/themes/maxiblocks/functions.php on line 489
[04-Jun-2024 16:31:07 UTC] PHP Fatal error:  Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, WP_REST_Request given in /home/dasaguyuro9895/web/maxitheme.instawp.xyz/public_html/wp-content/plugins/maxi-blocks/core/class-maxi-api.php:594
Stack trace:
#0 /home/dasaguyuro9895/web/maxitheme.instawp.xyz/public_html/wp-includes/rest-api/class-wp-rest-server.php(1230): MaxiBlocks_API->post_maxi_blocks_sc_string()
#1 /home/dasaguyuro9895/web/maxitheme.instawp.xyz/public_html/wp-includes/rest-api/class-wp-rest-server.php(1063): WP_REST_Server->respond_to_request()
#2 /home/dasaguyuro9895/web/maxitheme.instawp.xyz/public_html/wp-includes/rest-api/class-wp-rest-server.php(439): WP_REST_Server->dispatch()
#3 /home/dasaguyuro9895/web/maxitheme.instawp.xyz/public_html/wp-includes/rest-api.php(428): WP_REST_Server->serve_request()
#4 /home/dasaguyuro9895/web/maxitheme.instawp.xyz/public_html/wp-includes/class-wp-hook.php(324): rest_api_loaded()
#5 /home/dasaguyuro9895/web/maxitheme.instawp.xyz/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#6 /home/dasaguyuro9895/web/maxitheme.instawp.xyz/public_html/wp-includes/plugin.php(565): WP_Hook->do_action()
#7 /home/dasaguyuro9895/web/maxitheme.instawp.xyz/public_html/wp-includes/class-wp.php(418): do_action_ref_array()
#8 /home/dasaguyuro9895/web/maxitheme.instawp.xyz/public_html/wp-includes/class-wp.php(813): WP->parse_request()
#9 /home/dasaguyuro9895/web/maxitheme.instawp.xyz/public_html/wp-includes/functions.php(1336): WP->main()
#10 /home/dasaguyuro9895/web/maxitheme.instawp.xyz/public_html/wp-blog-header.php(16): wp()
#11 /home/dasaguyuro9895/web/maxitheme.instawp.xyz/public_html/index.php(17): require('...')
#12 {main}
  thrown in /home/dasaguyuro9895/web/maxitheme.instawp.xyz/public_html/wp-content/plugins/maxi-blocks/core/class-maxi-api.php on line 594
  
----

Code editor

```
<!-- wp:template-part {"slug":"header","theme":"maxiblocks"} /-->

<!-- wp:group {"tagName":"main","align":"full","style":{"spacing":{"padding":{"top":"0","bottom":"0","left":"0%","right":"0%"}}},"layout":{"type":"constrained"}} -->
<main
	class="wp-block-group alignfull"
	style="
		padding-top: 0;
		padding-right: 0%;
		padding-bottom: 0;
		padding-left: 0%;
	"
>
	<!-- wp:post-content {"style":{"spacing":{"blockGap":"0"}}} /-->
</main>
<!-- /wp:group -->

<!-- wp:template-part {"slug":"footer","tagName":"footer","area":"footer","theme":"maxiblocks"} /-->

```
======

Found this pattern export function from "My patterns" but there is no menu item for it? Odd
https://maxitheme.instawp.xyz/wp-admin/edit.php?post_type=wp_block
![image](https://github.com/maxi-blocks/maxiblocks-theme/assets/7437580/89cc30f7-be0d-43e0-b6a5-af8f1cdb8fb3)

=====
Here ui styles are missing for some reason.
blob:https://maxitheme.instawp.xyz/03f61330-570d-4916-9d3d-8ab293cd8dad
![image](https://github.com/maxi-blocks/maxiblocks-theme/assets/7437580/62f06773-8153-464e-ae77-2c255997a1a9)

![image](https://github.com/maxi-blocks/maxiblocks-theme/assets/7437580/c17fcea5-fe75-45f0-a34a-dbb12bc9e21d)

===
THIS IS JUST COMMENTARY ON THE POST WRITING EXPERIENCE - not bugs. Just thoughts on how we might improve it. 

Made a new blog post and this happened with the single post template. 
https://maxitheme.instawp.xyz/hello-world/

![image](https://github.com/maxi-blocks/maxiblocks-theme/assets/7437580/6ae947d2-4ff3-42e8-980a-9164abb61d07)

> Realised the blog post template did not have a Gutenberg "Content" area to i tried to add one. Then the bg colour is white - even though i set it to black background ons the content block and on the Column Maxi which contains it. No change.
> https://maxitheme.instawp.xyz/hello-world/

**Aha i figured it out.** In the blog post Editing Experience EE you basically just use text, image, video (not container, row and column). You basically need to imagine the VE Visitor experience side and what it will look like. 

A new post https://maxitheme.instawp.xyz/wp-admin/post-new.php
Just gives you nothing - see screenshot. Is this still an FSE ui shortcoming? IE there is no solution for it yet? 
![image](https://github.com/maxi-blocks/maxiblocks-theme/assets/7437580/0d61f7a6-fadc-4ee2-aa35-70a1058ec4de)

Feels odd when the single blog post template is not loaded in the EE Visual editor when it is active. It make the writing experience odd. Is there an option to load it in the EE - i'm not sure how it works - just thinking of a way that will improve the user experience cos now its kinda weird. Not sure what can be done - its very different from the classic editor where you have an input field the the post content. When i get a blank page for a post it im srt of still in the "oh i have to design it" mode versus "just start writing. I wonder what we can do to make it more intuitive?

**Maybe it should feel more like a Writing Experience?** 
Lol i found "distraction free mode" under preferences and now i dont even have a save button.

![image](https://github.com/maxi-blocks/maxiblocks-theme/assets/7437580/f601e217-22a8-430d-a014-bdbb7e648070)
 
 Found it - you hover top of the screen then it shows the toolbar. In this view the Maxi Master Toolbar Icon doesn't work.
 
![image](https://github.com/maxi-blocks/maxiblocks-theme/assets/7437580/54e8129d-1a1a-404c-9fa5-417c2ed1916a)

Is there any way for themes or plugins to control the editor styles for the Blog writing Experience?

---

Ok that's all i have for now. More to follow.

**Comment by elzadj** [comment]
Check the plugin notice - Installation button (when the plugin is not installed)

**Comment by elzadj** [comment]
> Found this pattern export function from "My patterns" but there is no menu item for it? Odd
> https://maxitheme.instawp.xyz/wp-admin/edit.php?post_type=wp_block

![screenshot-wordpress local-2024 06 05-12_15_33](https://github.com/maxi-blocks/maxiblocks-theme/assets/2401618/be92424d-abbf-4eba-9f0b-8cf018d3408e)

**Comment by elzadj** [comment]
Summarizing the issues to fix: 

- [ ] https://github.com/maxi-blocks/maxi-blocks/issues/5570
- [ ] PHP error and deprecated according to the log
- [ ] A delay when creating a new post (it's back again :(((( )
- [ ] margin-block-start for content

**Comment by ckp267** [comment]
No pulses for me when inserting patterns from posts creation flow https://maxitheme.instawp.xyz/wp-admin/post-new.php
Just nothing and then it appears. Then when a try to CTRL A - Delete - then the pulse work when im trying to delete.

Warning: Internal React error: Expected static flag was missing. Please notify the React team.
is the console error. x 27

https://jam.dev/c/701417aa-4b0d-4963-8468-02436a8ea3e2

**Comment by elzadj** [comment]
> 3 problem - its when you edit "my patterns" "Here ui styles are missing for some reason."
> https://maxitheme.instawp.xyz/wp-admin/edit.php?post_type=wp_block

Still can't see / re-create it, so a video would be nice :pouting_cat:

**Comment by ckp267** [comment]
> > 3 problem - its when you edit "my patterns" "Here ui styles are missing for some reason."
> > https://maxitheme.instawp.xyz/wp-admin/edit.php?post_type=wp_block
> 
> Still can't see / re-create it, so a video would be nice 😾

Now i cannot recreate it either. Move on.
