### ISSUE TITLE
Feedback for MaxiBlocksTheme-Beta-v1-0-6

### ISSUE THREAD

**Issue by ckp267** [maxi-blocks/maxiblocks-theme#4]
**Environment:** 
WP Version | 6.5.4
PHP version | 8.2.7 (Supports 64bit values)
Client version | mysqlnd 8.2.7

**Steps taken:** 

1. Fresh WordPress installation - everything set to default.
2. Install MaxiBlocks Plugin
3. Install MaxiBlocks theme - _MaxiBlocksTheme-Beta-v1-0-6_

**Issue:** 
On theme activation there's a prompt "View site" which takes you to the **front page** - all styles are missing for the "front page template"
- Suspect it relates to the wordpress install **default** "reading settings" see screenshot. 
- Settings default to "latest blog posts".
- To solve it i had to open the **front page** in site editor. Then click on some text. Change some text to get the "save" button to become active - then "save" the page - then the styles worked as expected. 
![image](https://github.com/maxi-blocks/maxiblocks-theme/assets/7437580/789eaad3-d937-4c44-9596-f1d68c174e17)
![chrome_zuIUclVBVw](https://github.com/maxi-blocks/maxiblocks-theme/assets/7437580/23a2af87-c454-4f8c-8e87-efaaae908ff4)
![chrome_y8zNdOF0T8](https://github.com/maxi-blocks/maxiblocks-theme/assets/7437580/af774e74-680d-43c2-9de5-ae8af83236e3)

**Comment by elzadj** [comment]
I think, logically, if it's set to the latest posts, we need to show the Blog template here, not the static front page without the latest posts.

**Comment by ckp267** [comment]
> I think, logically, if it's set to the latest posts, we need to show the Blog template here, not the static front page without the latest posts.

You're probably right, but then it will only display the default "Hello World" post if they haven't deleted it yet. This is essentially the theme onboarding flow, and regardless of what we choose, we can't show an unstyled page.

Some users will already have posts and settings, so we should respect their choices. I feel we should stick with the existing **"New theme activated. [Visit site](https://theme106test.instawp.xyz/)"** visit site notice, as most people will click that. 

UNLESS WE are the ones showing that NOTICE with the Link? anyways the homepage should not be broken id it uses our template. (Cant imagine what Divi or Elementor will look like if you activate the MaxiTheme lol.)

See screenshots 
![image](https://github.com/maxi-blocks/maxiblocks-theme/assets/7437580/9f4dcf63-1a1f-4803-ae70-2184c03b9ad7)

**Comment by elzadj** [comment]
Fixed in the new version
